### ISSUE TITLE
Crash with Forge 41.0.94+

### ISSUE THREAD

**Issue by MelanX** [r8420/MoreOverlays-updated#31]
This is due to the two breaking changes in Forge. 
Version: 1.21.1

**Comment by Jayryn** [comment]
@MelanX Your issue is fixed with #38. We have to wait until @r8420 will merge it.

**You can use my current release for 1.19 which is exactly the same as in the PR.**
https://github.com/drjayy/MoreOverlays-updated/releases/tag/v1.21.2

-> Please leave this issue open so it is used as reference for the PR (aka r8420 will see it)

**Comment by Jayryn** [comment]
@MelanX this issue can be closed as the PR is now officially merged

**Comment by r8420** [comment]
Should be fixed in [MoreOverlays 1.21.2](https://www.curseforge.com/minecraft/mc-mods/more-overlays-updated/files/3921860)
