### ISSUE TITLE
Error loading ( ... has failed to load correctly )

### ISSUE THREAD

**Issue by clementvt** [r8420/MoreOverlays-updated#32]
![Capture d’écran 2022-07-21 135330](https://user-images.githubusercontent.com/47658318/180208031-ce3c6ab5-c0b3-4892-92b7-82cc45041983.png)
with these mods

![image](https://user-images.githubusercontent.com/47658318/180208116-f6449600-9792-4af7-8b7e-625ee22012d6.png)
in 1.19

**Comment by Sanastae** [comment]
I have the same issue with the forge version.
Using Forge 41.0.107

**Comment by Jayryn** [comment]
@Sanastae @Imperiator Your issue is fixed with #38. We have to wait until @r8420 will merge it.

**You can use my current release for 1.19 which is exactly the same as in the PR.**
https://github.com/drjayy/MoreOverlays-updated/releases/tag/v1.21.2

-> Please leave this issue open so it is used as reference for the PR (aka r8420 will see it)

**Comment by Jayryn** [comment]
@Imperiator this issue can be closed as the PR is now officially merged

**Comment by r8420** [comment]
Should be fixed in [MoreOverlays 1.21.2](https://www.curseforge.com/minecraft/mc-mods/more-overlays-updated/files/3921860)
