### ISSUE TITLE
Lighting feature not working (F7 key)

### ISSUE THREAD

**Issue by Subratrix** [r8420/MoreOverlays-updated#4]
I see a lot of others are having issues with the lighting overlay enabled by the F7 key, I'm having that issue as well. I'm using Forge for Minecraft 1.16.3 version 34.0.9 and using More Overlays Updated version 1.18.8 (the Alpha version for Minecraft 1.16.3). The only other mods I am currently using are AppleSkin (shows hunger saturation and what saturation food gives you), VoxelMap, OptiFine, and OptiForge. The F9 function to see chunk borders still works fine though. I even tried rebinding the key from F7 to a key that was unused, no luck. I know Alpha means that it is still in early testing phases, so I understand. Please let me know if there is anything I can do to help (though I have no knowledge of coding).

**Comment by Gbergz** [comment]
Can confirm, not working on **1.16.3** Forge version **34.1.14**
Mod version: **moreoverlays-1.18.8-mc1.16.3.jar**

**Comment by r8420** [comment]
I'm not able to replicate this issue. There was another person who had problems with the mod for 1.16.3 and I tried using the exact same mods, same mod versions, same forge version, same Minecraft version and even the same java version as him, but I was not able te replicate the problem.
I also tried it on 2 different PC's with a clean Minecraft and Forge installation but still no success. Are you also having the same problem on 1.16.2? Because the only things that's different between the mc1.16.2 version of the mod and the mc1.16.3 version are the dependencies.

Here are also 2 test versions that may fix the problem so please try them:
[moreoverlays-1.18.9 Test Versions-mc1.16.3.zip](https://github.com/r8420/MoreOverlays-1.15/files/5372755/moreoverlays-1.18.9.Test.Versions-mc1.16.3.zip)

If I can't replicate the problem, it's almost impossible for me to fix it.

**Comment by Gbergz** [comment]
Problem went away when using the modfile ``moreoverlays-1.18.9_PREVIEW_1-mc1.16.3.jar``
It now shows the lightlevel overlay again.

**Comment by r8420** [comment]
That's great! Fixed an issue without even being able to replicate the issue, that doesn't happen everyday. I've uploaded the file to CurseForge: https://www.curseforge.com/minecraft/mc-mods/more-overlays-updated/files/3079188. @Subratrix Please reopen this issue if you're still having this problem.

**Comment by Greg-21** [comment]
I have the same issue, and version 1.18.9 of this mod still hasn't fixed it. For comparison, the chunk boundary overlay works almost correctly (the only issue I noticed are clouds rendering in front of the overlay).

**Comment by taj1994** [comment]
I'm having the same issue. I'm using 1.18.9 (the version that supposedly fixed it) and Forge 34.1.35, and the light level overlay doesn't work while connected to a server, but chunk borders work just fine. The behaviour is the same whether or not I'm using any other mods

It also doesn't seem matter whether it's a vanilla server or not. If it's a server, it doesn't work. If it's single-player, it works fine

**Comment by Greg-21** [comment]
> It also doesn't seem matter whether it's a vanilla server or not. If it's a server, it doesn't work. If it's single-player, it works fine

For me, the light level overlay doesn't work in singleplayer either.

**Comment by Greg-21** [comment]
> It also doesn't seem matter whether it's a vanilla server or not. If it's a server, it doesn't work. If it's single-player, it works fine

For me, the light level overlay doesn't work in singleplayer either :/

**Comment by r8420** [comment]
I'm able to replicate the problem and trying to fix it. It's a really strange issue. I'll keep you guys notified about the progress.

**Comment by r8420** [comment]
Just released a new version with bugfixes: [https://www.curseforge.com/minecraft/mc-mods/more-overlays-updated/files/3099374](https://www.curseforge.com/minecraft/mc-mods/more-overlays-updated/files/3099374) It should work again on servers.

**Comment by taj1994** [comment]
1.18.10 works perfectly for me

**Comment by Subratrix** [comment]
1.18.10 works great for me as well! Thank you so much!
